'use client';
import {ArrowRight,Check,ChevronDown,Mail,Menu,MessageCircle,Quote,X} from 'lucide-react';
import {CSSProperties,FormEvent,PointerEvent,useEffect,useState} from 'react';
import RevealPortrait from './RevealPortrait';
const services=[
{tag:'理清方向',name:'品牌诊断',price:'¥ 1,299',note:'一次 90 分钟深度咨询',fit:'适合定位模糊、内容散乱，想快速找到突破口的你',items:['个人品牌现状诊断','定位与目标客群梳理','内容与产品问题拆解','一份可执行的行动清单']},
{tag:'最受欢迎',name:'品牌共创',price:'¥ 6,800',note:'4 周一对一陪跑',fit:'适合准备认真经营个人品牌，并开始稳定获客的你',items:['差异化定位与品牌主张','内容支柱与选题系统','服务产品与定价设计','主页文案与视觉方向','4 次一对一策略会议']},
{tag:'长期增长',name:'品牌顾问',price:'¥ 16,800',note:'12 周战略顾问服务',fit:'适合已有业务基础，想系统升级品牌和商业模式的你',items:['品牌共创全部内容','季度增长路线图','内容与产品持续复盘','关键页面与方案审阅','工作日顾问答疑支持']}];
const testimonials=[['以前总觉得自己什么都能做，却说不清为什么客户要选我。和郝帅梳理后，我第一次有了清晰定位，两个月内咨询单价提升了 60%。','林蔚','独立设计师'],['不是给我一套模板，而是真正理解我的业务。新的内容框架让我不再每天焦虑发什么，也开始收到更精准的客户主动咨询。','陈默','职场教练'],['最有价值的是把“专业能力”变成了客户听得懂、愿意买的服务。现在团队所有对外表达都更统一，成交沟通也轻松很多。','周晴','精品民宿主理人'],['郝帅既懂品牌，也懂一人公司的现实限制。给出的每一步都能落地，没有空洞概念，让我少走了很多弯路。','王野','商业摄影师']];
const faqs=[['我还没有开始做个人品牌，适合咨询吗？','适合。越早建立清晰的定位与表达，越能避免后续反复推倒重来。品牌诊断尤其适合从零开始或正处在转型期的人。'],['你会直接帮我写文案、做设计吗？','品牌共创和长期顾问包含核心页面文案框架与视觉方向建议，但不包含完整代运营和视觉执行。如有需要，我可以推荐长期合作的专业伙伴。'],['咨询前需要准备什么？','预约确认后你会收到一份简短问卷。只需如实填写你的经历、业务现状、目标和困惑，我会在会前完成基础研究。'],['多久能看到效果？','定位和表达的变化通常可以立刻感受到；稳定获客则取决于你的执行频率、原有基础和业务周期。大多数共创客户会在 1-3 个月内看到明显变化。'],['如果咨询后发现不适合怎么办？','正式合作前会先进行 20 分钟沟通，确认需求和匹配度。如果我判断自己不适合解决你的问题，会直接说明并给出其他建议。'],['可以开发票吗？','可以。所有服务均可开具正规电子发票，签约后对公付款，具体信息会写入服务协议。']];
export default function Home(){const[menu,setMenu]=useState(false);const[openFaq,setOpenFaq]=useState<number|null>(0);const[sent,setSent]=useState(false);const[reveal,setReveal]=useState({x:50,y:50,active:false});useEffect(()=>{const nodes=document.querySelectorAll('.section,.contact,.serviceGrid article,.storyGrid article');nodes.forEach(node=>node.classList.add('motion-ready'));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('motion-in');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -60px'});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);const moveReveal=(e:PointerEvent<HTMLDivElement>)=>{const rect=e.currentTarget.getBoundingClientRect();setReveal({x:((e.clientX-rect.left)/rect.width)*100,y:((e.clientY-rect.top)/rect.height)*100,active:true})};const revealStyle={'--reveal-x':`${reveal.x}%`,'--reveal-y':`${reveal.y}%`} as CSSProperties;const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};const nav=[['关于我','#about'],['服务','#services'],['客户故事','#stories'],['常见问题','#faq']];return <main>
<header className="nav"><a href="#top" className="brand"><span>H</span> 郝帅</a><nav>{nav.map(([n,h])=><a key={n} href={h}>{n}</a>)}</nav><a className="navCta" href="#contact">预约咨询 <ArrowRight size={15}/></a><button className="menuBtn" aria-label="打开菜单" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<div className="mobileNav">{nav.map(([n,h])=><a key={n} href={h} onClick={()=>setMenu(false)}>{n}</a>)}<a href="#contact">预约咨询</a></div>}
<section className="hero" id="top"><div className="heroGrid"/><div className="heroCopy"><div className="eyebrow"><span/> 一人公司 · 品牌增长顾问</div><h1>让你的专业，<br/>成为客户选择你的<span>理由。</span></h1><p>我是郝帅，个人品牌顾问。帮自由职业者和小商家理清定位、建立表达，让好能力被看见，也让个人品牌真正带来生意。</p><div className="heroActions"><a className="btn primary" href="#services">了解服务 <ArrowRight size={17}/></a><a className="btn secondary" href="#contact">预约咨询</a></div><div className="trust"><b>80<sup>+</sup></b><span>位个人品牌<br/>完成清晰升级</span><i/><b>4.9</b><span>客户平均<br/>服务评分</span></div></div><div className="heroVisual"><RevealPortrait/></div></section>
<section className="section about" id="about"><div className="sectionNo">01 / 关于我</div><div className="aboutLead"><h2>我相信，真正有生命力的品牌，<br/>都始于一个<span>清晰的人。</span></h2></div><div className="aboutBody"><div className="bio"><p>过去 8 年，我从品牌策划、内容营销到商业咨询，参与过从初创团队到成熟企业的品牌项目。后来我发现，个人品牌最难的从来不是“怎么包装”，而是如何把一个人的经历、能力与市场需求，连接成清晰的价值。</p><p>现在，我专注服务认真做事的自由职业者、小商家和知识型创业者。陪你从“我会很多”走向“客户一眼就知道为什么选你”，建立一套真实、可持续，也能产生商业回报的个人品牌系统。</p></div><div className="capabilities">{[['8 年','品牌与内容经验'],['80+','一对一咨询客户'],['12 个','覆盖行业领域'],['65%','来自客户转介绍']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div><div className="principles"><span>我能帮你的</span>{[['01','找到差异','从经历和能力中提炼真正属于你的竞争优势。'],['02','说清价值','把专业术语变成客户听得懂、记得住的表达。'],['03','形成生意','让内容、服务与成交路径成为一个完整系统。']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section className="section services" id="services"><div className="sectionHead"><div><div className="sectionNo">02 / 服务内容</div><h2>从一次理清，<br/>到长期增长。</h2></div><p>不卖标准答案。根据你所在的阶段，<br/>一起解决当下最重要的品牌问题。</p></div><div className="serviceGrid">{services.map((s,i)=><article className={i===1?'featured':''} key={s.name}><div className="serviceTag">{s.tag}</div><h3>{s.name}</h3><div className="price">{s.price}</div><small>{s.note}</small><p>{s.fit}</p><ul>{s.items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a href="#contact">选择这项服务 <ArrowRight size={16}/></a></article>)}</div></section>
<section className="section stories" id="stories"><div className="sectionHead"><div><div className="sectionNo">03 / 客户故事</div><h2>他们开始，更清晰地<br/>被世界看见。</h2></div><div className="bigQuote">“</div></div><div className="storyGrid">{testimonials.map((t,i)=><article key={t[1]}><Quote size={22}/><p>{t[0]}</p><div className="person"><span>{t[1][0]}</span><div><b>{t[1]}</b><small>{t[2]}</small></div></div><em>0{i+1}</em></article>)}</div></section>
<section className="section faq" id="faq"><div className="faqIntro"><div className="sectionNo">04 / 常见问题</div><h2>合作之前，<br/>你可能想知道。</h2><p>还有其他问题？欢迎直接写信给我。</p><a href="mailto:hello@haoshuai.cn">hello@haoshuai.cn <ArrowRight size={15}/></a></div><div className="faqList">{faqs.map((f,i)=><button key={f[0]} onClick={()=>setOpenFaq(openFaq===i?null:i)} className={openFaq===i?'active':''}><div><span>0{i+1}</span><b>{f[0]}</b><ChevronDown size={20}/></div><p>{f[1]}</p></button>)}</div></section>
<section className="contact" id="contact"><div className="contactCopy"><div className="sectionNo light">05 / 开始合作</div><h2>你的好能力，<br/>值得被更多人看见。</h2><p>填写右侧表单，简单说说你的现状和困惑。我会在 2 个工作日内回复，并与你约一次 20 分钟免费沟通。</p><div className="contactWays"><a href="mailto:hello@haoshuai.cn"><Mail/><span><small>邮箱</small>hello@haoshuai.cn</span></a><div><MessageCircle/><span><small>微信</small>haoshuai_brand</span></div></div></div><form onSubmit={submit}>{sent?<div className="success"><Check/><h3>收到你的预约了</h3><p>我会在 2 个工作日内通过你留下的联系方式与你联系。</p><button type="button" onClick={()=>setSent(false)}>再提交一份</button></div>:<><div className="fieldRow"><label>怎么称呼你？<input required placeholder="你的姓名"/></label><label>你的联系方式<input required placeholder="微信 / 手机 / 邮箱"/></label></div><label>你目前的身份<select required defaultValue=""><option value="" disabled>请选择</option><option>自由职业者</option><option>小商家 / 主理人</option><option>知识型创业者</option><option>职场转型中</option><option>其他</option></select></label><label>你最想解决的问题是什么？<textarea required rows={4} placeholder="简单说说你的现状、目标和困惑……"/></label><button className="submit" type="submit">提交预约 <ArrowRight size={17}/></button><small className="privacy">提交即表示你同意我仅将这些信息用于本次咨询沟通。</small></>}</form></section><footer><a href="#top" className="brand"><span>H</span> 郝帅</a><p>把专业变成品牌，把品牌变成长期生意。</p><div>© 2026 郝帅个人品牌咨询</div></footer></main>}
